### ISSUE TITLE
Serverless support for the terraform pinceone provider

### ISSUE THREAD

**Issue by dinuka-rp** [thiskevinwang/terraform-provider-pinecone#14] opened 2024-03-13 02:50 UTC
Pinecone serverless looks tempting to me as I manage multiple client instances that don't necessarily need pods. However, the lack of support for regions is keeping me from moving all my vector-db instances to serverless.

I would like to manage all my infrastructure, including pinecone vector indexes. But, I'm a bit concerned that serverless support might take too long for the Terraform provider.

I'm a bit of a newbie to Terraform and I doubt I'll have enough time to come up with a work-around for this provider. Would appreciate any guidance. I might just stick to using the Pinecone API to manage indexes if this provider won't get updated.

**Comment by thiskevinwang** [comment] 2024-03-13 03:17
Hey @dinuka-rp, Serverless appears to be in public preview. See this comment https://github.com/thiskevinwang/terraform-provider-pinecone/issues/13#issuecomment-1974860745

---

Closing as duplicate of #13

**Closed as completed by thiskevinwang** 2024-03-13 03:17 UTC
